language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.grails/wrapper"
  - "$HOME/.grails/caches"
  - "$HOME/.m2"
script: "./travis.sh"
env:
  global:
    secure: caF9y/rgf3OG2sikCEgHwfBP+lnjR4XvXyqGa3al9ZUXCOM9554cDp7vkeGyU69/X4AtfG/Wlu1wtkNV5B5I9GoHZZ7o2oYphf1J8sueWV14hxnI27fVhrU25p8HZU9CXCZm1FIpwfZdZo08EdqZ3IUDk+z4ia7tr2deQyocU/imhmEShoQFsiDqv5NzyoVKbtE4vX9pxFIx8ojlF20WNmU7j8mNvaCpitgMPlrM8+LbieLteXeYRc9shhqI0xcGKQYWH/E5oOTg8OdhStROrM40rA8Xyd8XFSJKBHrf0XBEHGscQVLIdjzAHlYVKPjKDGzb8AlezS2EnTaSSiR0eRImkCm+lXLE9tWKINleDSj7CWzThAuZfKyXrp1k6KS/UGfA1txx/LSwl7owftPmIn2kmoqq+aohWdrjpUc1Mw32EGqy4X+wMyn32wUfDUrbbGtIWUmEFjEhtHVfS5XprA/QvquqJ8tFsyColvUDTjwTHHLWA6W8XdZ/zj4xhcYX0Qw8EqaVkAYBMFRtSLyCH7ghS4F3UTH48VCQ6hmfJnq6P5YrggLzyBxwEqflVFQEVxlFPWgDEr4+0Vm5HqULet2jsb67ixahmycyj/IcMWgInksWI5QNhjNpm3RxpO3r5XYTDLzRX2mnvSfFbb+utjRofrqdFGtZDDJen90J4Ag=
